version: '3.8'
services:

  db:
    image: mysql:8.0.27
    environment:
      DATABASE_HOST: docker-mysql
      DATABASE_POST: 3306
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: bitspeed
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

  app:
    image: qwerty098qwer/identityreconciliation:1.0
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/bitspeed
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - db